### ISSUE TITLE
bcrypt module error

### ISSUE THREAD

**Issue by ghost** [DimitriMikadze/Mean-Blog#2]
Pulled repo and ran npm install plus node app, I'm getting this error:

/Users/my-username/Mean-Blog/server/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
                  ^

Error: dlopen(/Users/my-username/Mean-Blog/server/node_modules/bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
        /Users/my-username/Mean-Blog/server/node_modules/bcrypt/build/Release/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/my-username/Mean-Blog/server/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/my-username/Mean-Blog/server/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/my-username/Mean-Blog/server/models/user.js:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Could the bcrypt module need a certain version to run this Mean- Blog?

**Comment by DimiMikadze** [comment]
I'm sorry i don't know whats your problem, there is written bcrypt module version in package.json file

**Comment by ghost** [comment]
While following the instructions the app fails to start due to the error above.

**Comment by DimiMikadze** [comment]
go do server directory and run npm install bcrypt

**Comment by JimmyLv** [comment]
still got the same error
