### ISSUE TITLE
Mongod dependency missing

### ISSUE THREAD

**Issue by buddies2705** [DimitriMikadze/Mean-Blog#3]
i am new to node. while running i am getting "node app.js"  below error 
 
module.js:472
    throw err;
    ^

Error: Cannot find module 'regexp-clone'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gauravagarwal/Mean-Blog/server/node_modules/mongoose/lib/utils.js:6:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

I tried installing mongod dependency but still getting the same error ..should i add mongod dependency on package.json and try to reinstall the app?

**Comment by buddies2705** [comment]
you can close it ..i forgot to run  npm install .
